### ISSUE TITLE
About setting CP936/950 in fonts

### ISSUE THREAD

**Issue by NightFurySL2001** [doggy8088/MicrosoftYaHeiMono-CP950#1]
I have found a new font to go with Microsoft Yahei and planned to combine them together, but I have a bit trouble setting the codepage up that it can be used persistantly in cmd. How can I set a font to support CP935/950 in font? Thanks in advance.

**Comment by doggy8088** [comment]
What font tool do you use?

**Comment by NightFurySL2001** [comment]
FontForge and FontLab

**Comment by doggy8088** [comment]
You need one of them to change codepage in the font file.

**Comment by NightFurySL2001** [comment]
How do i change it? I didnt found codepage settings in FontForge or FontLab.

**Comment by doggy8088** [comment]
Sorry, I totally forget how to change it. I made this font two years ago. I just remember this isn't a easy way to do. I took a lot of time to achieve this.

**Comment by NightFurySL2001** [comment]
Ok thanks. Also I found it in FontLab X'D. Just updated it and it appeared in Font Info.

**Comment by doggy8088** [comment]
Ha, nice to hear this! 😄

**Comment by doggy8088** [comment]
Can you share screenshots or steps here?
